name: Feature
description: Functional component that satisfies a customer need, smaller than an epic, consists of one or more stories or tasks.
title: '[FEATURE]: short feature description'
labels: ["feature"]
# If you have the redhat.vscode-yaml extension next line will be marked as error
# Ignore it by now... it's an upstream bug https://github.com/SchemaStore/schemastore/issues/3737
projects: ["Sumwall/1"]
body:
  - type: markdown
    attributes:
      value: |
        Remember, always create a short-lived local branch: `git checkout -b <type>/#issueID-short-title`,
        when working on this new issue. See [GitHub workflow](https://github.com/Sumwall/sumwall.project/blob/main/02.technology/03.git-workflow.md)
  - type: textarea
    attributes:
      label: Objective of this feature
      description: What do you expect to happen?
      placeholder: Tell us your objective!
      value: "A description goes here!"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Acceptance criteria
      description: Optional
      placeholder: Describe the acceptance criteria
    validations:
      required: false
  - type: textarea
    attributes:
      label: Any related Issue
      description: Optional
      placeholder: List the tasks related to this feature
      value: "* #issueId -  Related issue."
    validations:
      required: false
