name: Task - Bugfix
description: This task represents specific actions needed to complete in order to fix a bug.
title: '[bugfix]: short bug description'
labels: ["task", "bug"]
# If you have the redhat.vscode-yaml extension next line will be marked as error
# Ignore it by now... it's an upstream bug https://github.com/SchemaStore/schemastore/issues/3737
projects: ["Sumwall/1"]
body:
  - type: textarea
    attributes:
      label: Describe here the observed bug
      description: What do you expect to happen?
      placeholder: "A bug happened!"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Acceptance criteria
      description: Step by step guide about how to reproduce.
      placeholder: "How to reproduce:"
    validations:
      required: true
