name: Task - Documentation
description: Documenting features, tasks, architecture, howto's, etc. is extremely important
title: '[doc]: short issue description'
labels: ["task", "documentation"]
# If you have the redhat.vscode-yaml extension next line will be marked as error
# Ignore it by now... it's an upstream bug https://github.com/SchemaStore/schemastore/issues/3737
projects: ["Sumwall/1"]
body:
  - type: textarea
    attributes:
      label: Describe here the objective of this documentation task
    validations:
      required: true
